services:
  process-mongo:
    image: mongo:8
    container_name: argos-process-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - process_mongo_data:/data/db
    networks: [argos_net]
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://root:root@localhost:27017/admin",
          "--eval",
          "db.runCommand({ ping: 1 }).ok",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  process:
    image: ghcr.io/ervaal/argos-process-service:main
    # build:
    #   context: .
    #   dockerfile: process-bootstrap/Dockerfile
    container_name: argos-process
    environment:
      SPRING_MONGODB_URI: mongodb://root:root@process-mongo:27017/argos_process?authSource=admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      ARGOS_RESOURCE_GRPC_HOST: resource
      ARGOS_RESOURCE_GRPC_PORT: 9091
    depends_on:
      process-mongo:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks: [argos_net]

networks:
  argos_net:
    external: true

volumes:
  process_mongo_data:
